### ISSUE TITLE
[Обучение] Удалить неиспользуемые стили

### ISSUE THREAD

**Issue by annarv** [difetabe/forAnn-main#10]
Я заметила, что у тебя остались в проекте неиспользуемые стили. Это очень распространенная проблема в старых проектах - когда остаются "ошметки" каких-то старых решений и в "боевой" работе пригодится.
В PHPStorm есть функция - "Инспектор кода". Правая кнопка мыши на проекте - выбрать во всем проекте. В получившимся отчете посмотреть на что ругается система. В данном случае - увидь неиспользуемые стили и удали их. Ну и с другими пунктами ознакомся.

![image](https://user-images.githubusercontent.com/5478202/140943800-d7b225af-8dbc-4325-89a4-62222e19a119.png)

**Comment by difetabe** [comment]
Удобная штука)
