### ISSUE TITLE
[Обучение] Исключить из репозитория служебные файлы

### ISSUE THREAD

**Issue by annarv** [difetabe/forAnn-main#2]
В репозиторий попал файл .DS_Store - это служебный файл mac os, он не должен тут быть.
![image](https://user-images.githubusercontent.com/5478202/138760721-c063e32f-4ef2-42d0-84e6-0e47a352717d.png)

Соотвественно задача:
- убрать файл из репозитория
- ознакомиться с https://ru.hexlet.io/courses/git_base/lessons/git_gitignore/theory_unit и добавить подобные файлы.

**Comment by difetabe** [comment]
Я создала файл gitignore, проверь, пожалуйста. Это верное решение?

**Comment by annarv** [comment]
Надо удалить все, что не является частью проекта. сделать коммит и когда будешь смотреть какие файлы уходят в репозиторий - проверяй. Сейчас ты добавила их в гит, но на боевых проектах будут дрюкать если что-то лишнее будет попадать

**Comment by difetabe** [comment]
Теперь все, я сделала необходимое?
