### ISSUE TITLE
[Рефакторинг] [HTML] Хочу понять.

### ISSUE THREAD

**Issue by annarv** [difetabe/forAnn-main#33]
Я без сарказма. Хочу узнать ход твоих мыслей относительно 
![image](https://user-images.githubusercontent.com/5478202/145212388-3e804ffc-e4da-488f-aefd-cf479eb273b5.png)

у него абсолютное позиционирование и оно за видимой областью

**Comment by difetabe** [comment]
Это мы обсудили и, я так понимаю, можно закрывать
