### ISSUE TITLE
[Улучшения] Шрифты

### ISSUE THREAD

**Issue by annarv** [difetabe/forAnn-main#4]
Если по каким-то причинам, на страницу не подгружаются шрифты, то они заменяются на системные по-умолчанию. Соотвественно, важно указывать стандартный шрифт после целевого. Если дизайнер это не учел, то используется вариант -  "с засечками" или "без засечек".

Здесь все верно:
https://github.com/difetabe/forAnn-main/blob/master/index.html#L8

А здесь надо дополнить:
https://github.com/difetabe/forAnn-main/blob/master/styles.css#L137

И в других местах тоже.

**Comment by difetabe** [comment]
Дополнила
