### ISSUE TITLE
[Улучшение*] Сброс отступов браузера

### ISSUE THREAD

**Issue by annarv** [difetabe/forAnn-main#6]
Эта задача требует того, что бы ты сама выработала свое собственное отношение к данному вопросу. Я говорю о 
https://github.com/difetabe/forAnn-main/blob/master/styles.css#L1

В современном состоянии веб-браузеров это не такая острая тема "сброс стилей", но если к верстке будут требования старых браузеров, надо об этом помнить. 

Я хочу, что бы ты ознакомилась вот с [этой статьей ](https://medium.com/@stasonmars/%D1%81%D0%BE%D0%B2%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D1%8B%D0%B8%CC%86-%D1%81%D0%B1%D1%80%D0%BE%D1%81-css-f5816963c82b) и ознакомилась что и зачем человек делает. Свои собственные правила сброса сформируешь на практике, но пока, только прочесть и чекнуть.

**Comment by difetabe** [comment]
Прочла, добавила на всякий в закладки, чтобы попозже еще раз вернуться к этому
